name = "VisionHeatmaps"
uuid = "27106da1-f8bc-4ca8-8c66-9b8289f1e035"
authors = ["Adrian Hill <gh@adrianhill.de>"]
version = "1.1.0"

[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"

[compat]
ColorSchemes = "3"
ImageCore = "0.9, 0.10"
julia = "1.6"
